import fs from 'node:fs';
const { applications, engineering } = JSON.parse(fs.readFileSync(new URL('../app/project-catalog.json', import.meta.url), 'utf8'));
const table = applications.map(a => `| ${a.repository ? `[${a.title}](${a.repository})` : a.title} | ${a.description} | ${a.status}${a.repository ? '' : `; ${a.source.toLowerCase()}`} |`).join('\n');
const studies = engineering.map(e => `- **${e.repository ? `[${e.title}](${e.repository})` : e.title}** — ${e.description}`).join('\n');
const profile = `# Hi, I’m Sunil\n\nI build applications across AI, learning, finance, and media production. I also explore backend systems, event modelling, and the engineering underneath useful products.\n\n[Explore the portfolio source](https://github.com/sunilnjc/personal-website)\n\n## Applications & prototypes\n\n${applications.length} projects, with their current scope made explicit. Some are working applications; others are local prototypes. Private-source projects are described here without exposing their code or data.\n\n| Project | What it does | Stage |\n| --- | --- | --- |\n${table}\n\n## Engineering explorations\n\n${studies}\n\n## Notes from the work\n\n- **Separate guidance from diagnostics.** A camera operator needs one clear cue; detailed evidence belongs in the report.\n- **Keep a replayable history.** An immutable journal lets a ledger rebuild its projections and distinguish when an event happened from when it became known.\n- **Make missing data visible.** Sensor and market-data tools should show unavailable or uncertain results explicitly.\n\n## Connect\n\nFind my public repositories here on [GitHub](https://github.com/sunilnjc).\n\n*Project scope reviewed against implementation documentation in September 2026.*\n`;
fs.mkdirSync(new URL('../docs/', import.meta.url), { recursive: true });
fs.writeFileSync(new URL('../docs/github-profile.md', import.meta.url), profile);
fs.writeFileSync(new URL('../docs/PROJECTS.md', import.meta.url), `# Project collection\n\nThe website and GitHub profile are generated from \`app/project-catalog.json\`.\n\n| Project | What it does | Stage |\n| --- | --- | --- |\n${table}\n\n## Engineering explorations\n\n${studies}\n`);
console.log(`Generated profile for ${applications.length} applications and ${engineering.length} engineering projects.`);
